name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install gdtoolkit
        run: |
          pip install gdtoolkit

      - name: Run linter and formatting checks
        run: |
          ./lint.sh

      - name: Set up Godot 4
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.7.2
          use-dotnet: false

      - name: Run GUT Headless Tests
        run: |
          godot --headless -s addons/gut/gut_cmdln.gd -gexit -gconfig_file=res://.gutconfig.json
